- CHANGELOG.md
- lifelines/estimation.py
- lifelines/tests/test_estimation.py
- lifelines/tests/test_utils.py
- lifelines/utils.py
This PR adds: 
- Added new penalization scheme to AalenAdditiveFitter. You can now add a smoothing penalizer
that will try to keep subsequent values of a hazard curve close together. The penalizing coefficient
is `smoothing_penalizer`. 
- Changed `penalizer` keyword arg to `coef_penalizer` in AalenAdditiveFitter.
- new `ridge_regression` function in `utils.py` to perform linear regression with l2 penalizer terms.
> Adding smoothing penalizer to aalen

- lifelines/_utils/_cindex.f90
- lifelines/_utils/cindex.py
- lifelines/tests/test_estimation.py
A pair which is tied (time_a == time_b) is not an informative pair and
should be ignored.
> Math was not entirely correct in C-index

- lifelines/statistics.py
- lifelines/tests/test_statistics.py
- lifelines/utils.py
This change is in the spirit of earlier changes to allow normalized
times to be used without issues. Creates birth times as the minimum
death time instead of "zero".
Also changed a bunch of 'max' to 'np.max' to get moar speed.
Associated issue: #129
> Make logrank test work with negative death times

- lifelines/tests/test_utils.py
- lifelines/utils.py
Often cross_validation is used to compare different models. In such
cases it often desired that all models train on the same data to
make the comparison worthwile.
Scores can now also be anything return by the evaluation function.
One might for example want to compare more than one measure, in which
case a scalar is far too restricting. It is now even possible to just
have the evaulation method dump the validation output and perform
any numerical comparisons later.
Signed-off-by: Jonas Kalderstam <jonas@kalderstam.se>
> Allow multiple models in k_fold_cross_validation

- CHANGELOG.md
- lifelines/estimation.py
- lifelines/statistics.py
- lifelines/tests/test_estimation.py
- lifelines/tests/test_statistics.py
- setup.py
What started off as a minor patch has turned into a bit more. Changes:
- statistical tests in `lifelines.statstics`. now return a `StatisticalResult` object with properties like `p_value`, `test_results`, and `summary`.  
- removed `suppress_print` kwarg in statistical tests. 
- fixed a bug in how log-rank statistical tests are performed. The covariance matrix was not being correctly calculated. This resulted in slightly different p-values. 
- `WeibullFitter`, `ExponentialFitter`, `KaplanMeierFitter` and `BreslowFlemingHarringtonFitter` all have a `conditional_time_to_event_` property that measures  the median duration remaining until the death event, given survival up until time t.
@spacecowboy for review please!
> Version 0.7.0

- lifelines/__init__.py
- lifelines/version.py
- setup.py
this allows to have a __version__ attribute in the module
> get the version from version.py

- lifelines/estimation.py
- lifelines/tests/test_estimation.py
Thanks for making such a cool library!
I have some data with a lot of highly correlated attributes that I'd like to fit a Cox model to, so adding an L2 penalty seemed helpful. Maybe it'll be useful to other folks as well.
I'm happy to do more work on this if there's stuff I left out--just let me know!
> Add an l2 penalty option to Cox PH model

- docs/Survival Regression.rst
- lifelines/estimation.py
- lifelines/tests/test_estimation.py
This adds a `strata` keyword to `CoxPHFitter` to be used like R's strata:
```
Surv(rep(1, number_of_data_points_in_dataset), event_in_question) ~ predictor1 + predictor2 + strata(group_id)
```
see #148 for more details.
> strata for CoxPH

- lifelines/tests/test_utils.py
- lifelines/utils.py
- `datetimes_to_durations` now accepts a list as `na_values`, so multiple values can be checked. 
- fixed a bug in `datetimes_to_durations` where `fill_date` was not properly being applied.
- Changed warning in `datetimes_to_durations` to be correct. 
Closes #159
> Improvements to datetimes_to_durations

- CHANGELOG.md
- lifelines/estimation.py
- lifelines/version.py
- addition of a l2 `penalizer` to `CoxPHFitter`.
- dropped Fortran implementation of efficient Python version. Lifelines is pure python once again!
- addition of `strata` keyword argument to `CoxPHFitter` to allow for stratification of a single or set of 
categorical variables in your dataset.
- `datetimes_to_durations` now accepts a list as `na_values`, so multiple values can be checked. 
- fixed a bug in `datetimes_to_durations` where `fill_date` was not properly being applied.
- Changed warning in `datetimes_to_durations` to be correct. 
- refactor each fitter into it's own submodule. For now, the tests are still in the same file. This will also *not* break the API.
> 0.7.1 release

- lifelines/utils/__init__.py
- tests/test_estimation.py
whoop! Found a bug
- Kaplain Meier estimation of the CDF for left-censored data would give incorrect results if censorshop was present.
> fixing left censorship + improved test

- .travis.yml
- lifelines/generate_datasets.py
- lifelines/plotting.py
- tests/conftest.py
- tests/test_estimation.py
- tests/test_plotting.py
In response to #191, this PR allows the plotting tests to run on Travis. It tests all python versions (added 3.5) with both 1.4.3 and 1.5.0 of matplotlib.
Once 1.5.0 is released for real, the .travis file can be simplified. Atm it installs 1.5.0 with pip (requires extra apt-packages) and 1.4.3 via conda (quick and easy).
> Enable plotting tests on TravisCI

- .gitignore
- docs/Survival Regression.rst
- setup.py
It seems like setuptools is favored over distutils and allows things like installing in develop mode, which is handing when developing/debugging a package (I use that ability frequently). Setuptools isn't in the standard Python distro, but this package already has a ton of other dependencies; it seems reasonable to assume that setuptools is installed in whatever environment lifelines is deployed.
Thanks for an awesome project! I'm working on calculating lifetimes and have already found it very valuable (even just the documentation). I'm looking forward to contributing more.
> Use setuptools

- lifelines/fitters/exponential_fitter.py
- lifelines/fitters/weibull_fitter.py
- lifelines/utils/__init__.py
- lifelines/version.py
This adds two summary functions to `Weibull` and `Exponential` fitter, solves #224 
```
from lifelines import WeibullFitter
w = WeibullFitter()
s = np.random.weibull(2.5, size=10000)
w.fit(s)
w.summary
```
```
coef  se(coef)  lower 0.95  upper 0.95
lambda_  1.004762  0.004245    0.996441    1.013083
rho_     2.490955  0.019517    2.452694    2.529215
```
> Summaries + datetime_to_duration bug fix

- .travis.yml
- README.md
- dev-requirements.txt
Was enabling coverage on a new project and tried some copy paste from Lifelines and probably ran into the same problems you did (I am assuming you ran into the problems ;)
Also added some new Matploblib versions to the test matrix. (Btw, 2.0 is apparently in dev)
> Some test improvements

- setup.py
Adding this will allow libraries like [`caniusepython3`](https://pypi.python.org/pypi/caniusepython3) and [sites that rely on it](http://py3readiness.org/) to recognize that this library supports Python 3.
> Added explicit pypi trove classifiers for supported Python versions

- docs/Intro to lifelines.rst
- docs/Survival Analysis intro.rst
- docs/Survival Regression.rst
I've been reading the lifelines documentation (which is very educational!) and I found a few typos.
> Fix typos in documentation.

- lifelines/utils/__init__.py
`coerce=True` is rising deprecation warning when using pandas v0.17 and above, how about to use `errors='coerce'` instead?
> Fix deprecation warning

- docs/Survival Analysis intro.rst
In my previous pull request, there was a typo on line 54 that causes the math markup to be displayed as plain text. My apologies. I have fixed it in this change.
> Update Survival Analysis intro.rst

- CHANGELOG.md
- lifelines/fitters/coxph_fitter.py
- tests/test_estimation.py
- tests/utils/test_utils.py
New PR to replace #196 
cc @jstoxrocky and @IvanBarrientos
> Unique baseline hazard for each strata

- lifelines/fitters/coxph_fitter.py
- lifelines/utils/__init__.py
```
from lifelines import CoxPHFitter
from lifelines.datasets import load_rossi
rossi = load_rossi()
cp = CoxPHFitter()
%timeit cp.fit(rossi, 'week', 'arrest', strata=['race', 'paro', 'mar', 'wexp'])
%timeit cp.fit(rossi, 'week', 'arrest')
```
part of #271
> improve baseline survival performance

- lifelines/utils/__init__.py
- tests/utils/test_utils.py
[It is reported](https://github.com/CamDavidsonPilon/lifelines/issues/35) that the AalenAdditiveFitter is extremely slow for large matricies. Digging in, it seems like the solution to the ridge regression was explicitly computing the inverse, which is often [unnecessary in practice](https://www.johndcook.com/blog/2010/01/19/dont-invert-that-matrix/). This PR should reduce the runtime from O(n^3) to O(n^2) by not computing the inverse and instead solving the system of equations directly.
> solve linear system rather than explicitly computing inverse

- CHANGELOG.md
- lifelines/fitters/coxph_fitter.py
- lifelines/version.py
- tests/test_estimation.py
- corrected bug that was returning the wrong baseline survival and hazard values in `CoxPHFitter` when `normalize=True`. 
- removed  `normalize` kwarg in `CoxPHFitter`. This was causing lots of confusion for users, and added code complexity. It's really nice to be able to remove it.
- correcting column name in `CoxPHFitter.baseline_survival_`
- `CoxPHFitter.baseline_cumulative_hazard_` is always centered, to mimic R's `basehaz` API.
- new `predict_log_partial_hazards` to `CoxPHFitter`
Fixes: https://github.com/CamDavidsonPilon/lifelines/issues/289, https://github.com/CamDavidsonPilon/lifelines/issues/287
> Coxph baseline fix; remove normalize; bump version

- CHANGELOG.md
- lifelines/fitters/coxph_fitter.py
- lifelines/version.py
- tests/test_estimation.py
cc @disimone, can you try your code with this latest branch? 
I chose to keep normalisation in the library, but it is all transparent to the user. The reason to keep it is for numeric stability.
Fixes #294
> Fix scaling in cox ph prediction

- docs/Survival Regression.rst
adds python code for the first plot in the "Checking the proportional hazards assumption" section
fixes #322
> add code for cox assumption plot

- lifelines/utils/__init__.py
The training set in the k fold CV has the original column order, but when picking out the test set using testing_columns, the columns get sorted by pd.index.difference. --> switched to drop.
> difference also sorts columns

- docs/Examples.rst
Small grammar fix in the Examples documentation.
> #351 Replace "an plot" with "a plot".

- lifelines/fitters/aalen_additive_fitter.py
- lifelines/fitters/coxph_fitter.py
- tests/test_estimation.py
- tests/utils/test_utils.py
I've pickled a coxph model and it ended up with a large file size, I realized that the model stores the data inside it. This PR tries to address it, calculating training concordance and log partial hazard just after training, so it wouldn't need to store all the data anymore. I had to adapt some test cases that access the internal data too.
Is there any other reason to keep it? Is there a better way to approach this problem?
> Exclude data storage in model

- docs/Survival analysis with lifelines.rst
- lifelines/fitters/kaplan_meier_fitter.py
Added  'exponential Greenwood CI' to the documents. The link was also dead. I included another link about the method instead.
> Update Survival analysis with lifelines.rst

- lifelines/utils/__init__.py
- tests/utils/test_utils.py
There is an issue where `add_covariate_to_timeline` is filling `0` values downstream of accumulated sums instead of persisting the accumulated value. For example, the expected output of cumulatively summing `covariate_one` that enters following states `covariate_one = [1, 1, 1]` should be `cumsum_covariate_one = [0, 1, 2, 3, 3, ...]` if there are additional state changes of a different covariate after these events. However, the actual output is `cumsum_covariate_one = [0, 1, 2, 3, 0, ...]`. This is easy to reproduce by running code as in the test below, which would have failed previously.
This PR fixes the issue quick and easy.
> Properly forward fill cumulative sums when making covariate timeline

- lifelines/utils/__init__.py
- tests/test_estimation.py
Finally got around to checking KM for propensity scores/inverse probability weights. When running the KM fitter, if weights=df['weights'] is not converted to a np.array, then unexpected behaviors occur. I have rewritten survival_table_from_events to convert the specified weights to a np.asarray(). Without this change the user would have to specify weights=np.asarray(df['weights']). Results were compared to SAS and consistent results were obtained with this fix
> Fix error for IPW Kaplan Meier

- .travis.yml
Update the Travis CI to use an up to date version of Python3.7 instead of unreleased development version of 3.7
> use newer python 3.7

- CHANGELOG.md
- lifelines/fitters/cox_time_varying_fitter.py
- lifelines/fitters/coxph_fitter.py
- lifelines/version.py
- tests/test_estimation.py
- bug fix for the Cox model likelihood ratio test when using non-trivial weights.
> fix for likelihood ratio in cox models, v15.4

- lifelines/fitters/coxph_fitter.py
- lifelines/plotting.py
- lifelines/utils/__init__.py
- tests/test_estimation.py
For #577 
Ran formatter and addressed linting errors.
I added `_` underscores to the unused arguments but I would reccomend they just be removed and add a comment or TODO if they were meant as placeholders.
```
Messages
========
lifelines/fitters/coxph_fitter.py
Line: 619
pylint: unused-argument / Unused argument 'weights' (col 43)
Line: 717
pylint: unused-variable / Unused variable 'weighted_average' (col 12)
Line: 764
pylint: unused-argument / Unused argument 'T' (col 46)
Line: 1327
pylint: redefined-builtin / Redefining built-in 'help' (col 32)
Check Information
=================
Started: 2018-12-21 06:46:14.057368
Finished: 2018-12-21 06:47:00.913090
Time Taken: 46.86 seconds
Formatter: grouped
Profiles: .prospector.yaml, strictness_medium, strictness_high, strictness_veryhigh, …
```
> 0.16.0 Formatting and address linting errors

- lifelines/fitters/cox_time_varying_fitter.py
- lifelines/fitters/coxph_fitter.py
- lifelines/fitters/exponential_fitter.py
- lifelines/fitters/weibull_fitter.py
- lifelines/statistics.py
Fixes Issue #578 
There are currently a lot of broken tests on this branch.  These changes don't break any more tests, but once they're sorted out they may need further fixes for this stuff
I searched for all instances of `print_summary` - if they're named anything else I will have missed them
> Enforce 2DP when printing summary

- .travis.yml
- Makefile
- README.md
- reqs/dev-requirements.txt
Because of all the checks being done in the TravisCI things are getting a little bit flakey.
Made a few changes to hopefully reduce it's flakeyness like running the linters after the build has already succeeded. 
Something that could also help is to seperate some of the responsibilities. Right knowing that the Travis build failed doesn't mean very much. It could be some minor linting/formatting error, a dependency problem or actually a major bug. 
I suggest we start using [LGTM](https://lgtm.com/) as an additional CI tool in order to reduce some of the responsibility the TravisCI has. We can then also be more strict about failed Travis builds.  
https://lgtm.com/projects/g/CamDavidsonPilon/lifelines/alerts/?mode=list
I went ahead and added badges for it to the repo, but it still requires …
> ci_updates

- lifelines/fitters/aalen_johansen_fitter.py
- tests/test_estimation.py
Fixes for `AalenJohansenFitter` as mentioned in #629 and #630 Pointed to master branch, since no new version branches currently available
**What this adds:**
- More specific tied event detection. The type of ties that break Aalen-Johansen are tied event times of different events. Original code detected any ties, regardless of event type. New update only looks for ties where events are not the same
- Added tests to check the new event-detection process
- Variance calculation avoids problems when large sample sizes are provided. The potentially large divisions are spaced throughout the calculation to avoid overflow. Tested on sample size of 20,000+ and had no issues
- Variance calculation takes a long time, since the calculation requires iterating over every event time. This can make …
> Aalen johansen fixes

- lifelines/plotting.py
On the back of https://github.com/CamDavidsonPilon/lifelines/issues/666 👿 
It is a small change, but as mentioned in the issue it got me confused and I had to go through the source code and figure out what actually happens.
There is no clear indication in the code of why this inverse. The initial commit came in about 6 years ago from [here](https://github.com/CamDavidsonPilon/lifelines/commit/fa4c24456d83bef64858bf497b5cb8d08529ca37#diff-81b7d793b0503ee1c576beec8145aad6R47) . If that rings a bell I am more than happy to reconsider.
Here is the notebook I used for testing, as this particular point is not covered in the tests and I wasn't quite sure how to add it.
[notebook.zip](https://github.com/CamDavidsonPilon/lifelines/files/2984026/notebook.zip)
(had to compress due to GitHub not …
> Removed inversion of plotting lifetimes

- lifelines/fitters/aalen_additive_fitter.py
- lifelines/fitters/cox_time_varying_fitter.py
- lifelines/fitters/coxph_fitter.py
Before with an iteration, all the metrics were taking a new line. Now the numbers are printed in one line and can be seen as they change. Easier to look at especially when looking at Jupyter notebooks.
> Changed the way printing is done through iterations by flushing stdout

- reqs/base-requirements.txt
- setup.py
Fixed scipy version to <= 1.2.1 until autograd HIPS/autograd#490 is released. After that we could fix autograd to >= whatever version they release with that specific PR and return scipy to >=1.0.
In scipy >= 1.3.0 some functions that autograd uses are moved to a different namespace. Due to this change lifelines currently will not work when installed trough a package manager like pypi.
> Fixed scipy version to <=1.2.1

- lifelines/utils/__init__.py
The warning text refers to `lifelines.utils.datetime_to_durations` but should refer to `lifelines.utils.datetimes_to_durations` (notice "s" after datetime).
> Fixing reference in warning text for "unexpected datetype"

- docs/Survival analysis with lifelines.rst
There is no such method `hazard_confidence_intervals_`,
but there is a `smoothed_hazard_confidence_intervals_`.
> Fix typo in smoothing hazard curve docs

- lifelines/fitters/kaplan_meier_fitter.py
Lambda is slightly less performant and is also not picklable.
use the functools.partial instead that is the more robust way to
manage partial functions and functions using default arguments.
> kaplan_meier: Change lambda -> functools.partial()

- lifelines/utils/sklearn_adapter.py
X needs to be a dataframe currently. Print the type of X in the
exception message so it's clearer to users what is not supported.
Thought it would be a good idea, as sometimes I use this with other libraries that try to make pipelines with sklearn regressors - and Im just not sure what those other libraries are passing into lifelines (sklearn supports more inputs than lifelines - for example, sklearn supports numpy arrays)
> sklearn_adapter: Better error message for invalid X

- lifelines/fitters/__init__.py
- lifelines/utils/sklearn_adapter.py
- tests/test_estimation.py
For univariate models: `_hazard` is a property in the object, but actually a function - By making it a function, it becomes a part of the class definition and hence the pickle does not consider it as a property that needs to be serialized.
From my manual testing, these fitters can now be pickled:
- LogLogisticFitter
- WeibullFitter
- GeneralizedGammaFitter
Also, removed the xfail from the pickle and added joblib test cases in Univariate.
EDIT: I did some more digging and figured out the issue for the Regression models too.
For regression models: `_neg_likelihood_with_penalty_function` is a property in the object, but actually a function. By making it a functools.partial, pickle will know how to pickle it. Also, it needs the `unflatten` function which is an autograd function which cannot …
> Fix pickle issues

- lifelines/fitters/coxph_fitter.py
A small fix for the print_summary() function in coxph_fitter.py. Previously it fails with KeyError when alpha is not set to 0.05.
> Print summary fix

- lifelines/fitters/generalized_gamma_fitter.py
- lifelines/fitters/log_logistic_fitter.py
- lifelines/fitters/log_normal_fitter.py
- lifelines/fitters/piecewise_exponential_fitter.py
- lifelines/fitters/weibull_fitter.py
Since `median_survival_time_` was changed to `median_survival_time_` in 0.23.0, this updates the associated documentation.
> Changes `median_` to `median_survival_time_` in docs

- docs/Quickstart.rst
Updates `median_ ` to `median_survival_time_ `, to reflect change that happened in [0.23.0](https://lifelines.readthedocs.io/en/latest/Changelog.html#section-1)
> Updates to `median_survival_time_ ` in Quickstart

- lifelines/fitters/kaplan_meier_fitter.py
Since `median_` was changed to `median_survival_time_` in 0.23.0, this updates the associated documentation.
> Changes `median_`  to `median_survival_time_`

- lifelines/fitters/exponential_fitter.py
Since `median_survival_time_` was changed to `median_survival_time_` in 0.23.0, this updates the associated documentation.
> Updates `median_` to `median_survival_time_`

- MANIFEST.in
If not added, source installations created with `sdist`
don't work.
Fixes https://github.com/CamDavidsonPilon/lifelines/issues/900
> MANIFEST: Add "reqs"

- examples/README.md
There's also a `py` file there but I assume this should point at the notebook. There is no directory there (404).
> Add file extension to broken link.

- README.md
The CONTRIBUTING.md file moved and the link is broken.
> Point contributing url at new .github folder

- .github/CONTRIBUTING.md
- docs/Contributing.rst
The formatting in the bottom sections of the ['Contributing' page on readthedocs](https://lifelines.readthedocs.io/en/latest/Contributing.html#setting-up-a-lifelines-development-environment) is broken, resulting in the display of formatting characters and full urls. The contents should instead mirror the [github contributing page](https://github.com/CamDavidsonPilon/lifelines/blob/master/.github/CONTRIBUTING.md). The problems mostly stem from the fact that (unlike markdown) rst formatting cannot be nested, so you can't have something that's both italic and a link.
This PR is an example in one possible way to restructure things such that the contents appear more in line with the github based 'contributing' page, plus a couple of minor typo fixes.
> Remove nested rst formatting from contributing

- lifelines/utils/printer.py
Printing a CPH coefficient table is done using [`.to_latex()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_latex.html) (with no parameters). However, this means that the printed number have all decimals. With this fix, the number of printed decimals corresponds to the defined parameter `decimals`.
> Updated printer.py (LaTeX table with proper decimals)

- .travis.yml
- lifelines/datasets/__init__.py
- lifelines/tests/test_estimation.py
- setup.py
* Import collections from ABC instead of collections since it was removed in Python 3.9.
* Use raw string to fix a deprecation warning regrading invalid escape sequences.
> Add Python 3.9 compatibility

- lifelines/fitters/mixture_cure_fitter.py
- lifelines/tests/test_estimation.py
The MixtureCureFitter did not use the fit options of the base fitter. It should do so, so that it can take advantage of any necessary settings. The most obvious example of this is when the base_fitter=WeibullFitter - see new test for the rest.
> Use fit options from base fitter

- lifelines/fitters/kaplan_meier_fitter.py
- lifelines/fitters/nelson_aalen_fitter.py
- lifelines/plotting.py
- lifelines/statistics.py
- lifelines/tests/test_estimation.py
- lifelines/tests/test_plotting.py
- lifelines/tests/utils/test_utils.py
- lifelines/utils/__init__.py
Added plot_interval_censored_lifetimes function - similar to plot_lifetimes but for interval censored data. Example from doc string:
> Added plotting of lifetimes from interval censored data

- docs/index.rst
- lifelines/fitters/__init__.py
- lifelines/fitters/coxph_fitter.py
- lifelines/fitters/spline_fitter.py
- lifelines/statistics.py
- lifelines/tests/test_estimation.py
- lifelines/utils/printer.py
So this refactor places CoxPHFitter as a shell that calls out to two different models: SemiParametricPHFitter (new) and ParametricSplinePHFitter (renamed). These do almost all of the work. This abstraction, hopefully totally hidden from the end user, allows us to add new PH models in the future under this facade, and corrects the prediction and baseline problems users were having (#1032)
> Refactor CoxPHFitter

- docs/jupyter_notebooks/Modelling time-lagged conversion rates.ipynb
On line 474, I fixed a typo.
"I wasn't expect this good of a fit." -> "I wasn't expecting this good of a fit."
> Update Modelling time-lagged conversion rates.ipynb

- lifelines/fitters/__init__.py
Adopt new pandas behavior and silence deprecation warning. This can be quite noisy in fit if there's a datetime in your DataFrame for pandas >= 1.1.0.
Cf. https://github.com/pandas-dev/pandas/pull/34798
> Silence deprecation warning

- docs/Survival analysis with lifelines.rst
Per conversation in Gitter channel, changing the example from kmf.plot() to kmf.plot_cumulative_density in the left-censoring example.
> Correct Code Used in Left Censoring Example

- lifelines/tests/test_estimation.py
There is a small typo in lifelines/tests/test_estimation.py.
Should read `satisfy` rather than `statisfy`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, statisfy -> satisfy

- docs/Examples.rst
See issue #1196 - fixed the typo in `Examples.rst` and added sample codes for serialization to disk
> Updated model serialization examples

- reqs/base-requirements.txt
Formulaic has not yet committed to a stable API between major version bumps, and so to prevent future breakage, we constrain the version of formulaic we depend upon to the 0.2.x series. The minimum version we require is version 0.2.2 in order to resolve an issue with pandas indices being incorrectly respected in 0.2.1 .
closes #1215
> Constrain formulaic version to 0.2.x

- reqs/base-requirements.txt
pandas version under 1.0.5 is not compatible with numpy version 1.20.0, so I set an upper bound on numpy requirement.
See also [numpy issue #18355](https://github.com/numpy/numpy/issues/18355) and [pandas issue #39520](https://github.com/pandas-dev/pandas/issues/39520#issuecomment-772630011)
> Set upper bound for numpy 1.20.0

- CHANGELOG.md
- lifelines/plotting.py
- lifelines/tests/test_plotting.py
> adding collapsed version of lifetables when only showing a single summary row

- lifelines/fitters/__init__.py
- lifelines/utils/__init__.py
Bayesian Information Criteria (BIC) value is added as model prop: `model.BIC_`
`find_best_parametric_model()` 's `evaluation_lookup` now uses this prop for BIC value.
> add BIC_ prop

- .gitignore
- examples/cox_spline_custom_knots.py
- lifelines/fitters/coxph_fitter.py
I have added a new parameter in CoxPHFitter, named 'knots'. This parameter allows specifying the position of the knots in fitting process, instead of having the library automatically calculating it.
There's also an example file which shows how to use it, by fitting it to one week, a month and a year.
Finally this PR also adds the Pycharm .idea folder to the gitignore file.
> Added custom knots parameter for Cox Fitter

- CHANGELOG.md
- docs/Changelog.rst
- lifelines/fitters/cox_time_varying_fitter.py
- lifelines/fitters/coxph_fitter.py
- lifelines/fitters/kaplan_meier_fitter.py
- lifelines/plotting.py
- lifelines/tests/test_estimation.py
- lifelines/tests/test_plotting.py
- lifelines/tests/utils/test_utils.py
- lifelines/utils/__init__.py
- lifelines/version.py
- `.BIC_` is now present on fitted models.
- `CoxPHFitter` with spline baseline can accept pre-computed knot locations.
- Left censoring fitting in KaplanMeierFitter is now "expected". That is, `predict` _always_ predicts the survival function (as does every other model), `confidence_interval_` is _always_ the CI for the survival function (as does every other model), and so on. In summary: the API for estimates doesn't change depending on what your censoring your dataset is.
- Fixed an annoying bug where at_risk-table label's were not aligning properly when data spanned large ranges. See merging PR for details.
- Fixed a bug in `find_best_parametric_model` where the wrong BIC value was being computed.
- Fixed regression bug when using an array as a penalizer in Cox models.
cc @JoseLlanes …
> fix at_risk table bug, and bump version

- lifelines/tests/utils/test_utils.py
- lifelines/utils/__init__.py
Currently `utils.datetimes_to_durations` calculates durations for censored data in a way that leaks information. For example:
```
import lifelines
start_date = ["2013-10-08", "2013-10-09", "2013-10-10"]
end_date = ["2013-10-10", "2013-10-12", "2013-10-15"]
T, C = lifelines.utils.datetimes_to_durations(start_date, end_date, freq="D", fill_date="2013-10-12")
print(T), print(C);
```
gives:
```
[2. 3. 5.]
[ True  True False]
```
The last item is censored but the duration is calculated based on the provided end date. Consequently, duration calculation makes use of information that would not be available on the cutoff date and results in the the duration being longer than it should be (5 days instead of 2).
This PR attempts to adjust duration calculation for censored items so that information …
> Adjustment to how durations are calculated for events after cutoff date.

- lifelines/plotting.py
When working with hierarchical data, it makes sense to look at separate qq plots for each unit. By having a `scatter_color` argument, qq_plots of multiple units are easier to overlay in the same plot.
> added kwarg for scatter color to qq_plot

- lifelines/fitters/aalen_additive_fitter.py
- lifelines/fitters/cox_time_varying_fitter.py
Updated two of the iteration print statements that weren't to use linebreaks. Otherwise, the iterations get overwritten in a notebook and are jammed together in the terminal.
> Print with line break

- lifelines/fitters/aalen_additive_fitter.py
issue #1439 
In: lifelines/fitters/aalen_additive_fitter.py
line: 265
error: UnboundLocalError: local variable 'last_iteration' referenced before assignment.
Proposal: On line 226 add the declaration of the variable (i.e. last_iteration = 0)
> bugfix: 'last_iteration' not initialized

- docs/Survival analysis with lifelines.rst
I found the Kaplan-Meier example confusing about why the "death" event for JFK was unobserved, so felt adding that the retirement was "voluntary" would clarify the outcome of interest.
> EDIT regime example to clarify death event

- lifelines/fitters/__init__.py
- lifelines/fitters/aalen_johansen_fitter.py
***What does this PR fix?***
Running `plot()` when setting `calculate_variance=False` for the Aalen-Johansen estimator raises an error:
```python
from lifelines import AalenJohansenFitter
ajf = AalenJohansenFitter(calculate_variance=False)
ajf.fit(
df["duration"],
df["event"],
event_of_interest=2,
)
ajf.plot()
```
<details><summary>Full trace</summary>
```traceback
/Users/vincentmaladiere/INRIA/lifelines/lifelines/fitters/aalen_johansen_fitter.py:111: Warning: Tied event times were detected. The Aalen-Johansen estimator cannot handle tied event times.
To resolve ties, data is randomly jittered.
warnings.warn(
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[1], line 11
5 ajf = …
```
> Fix Aalen-Johansen plotting method when `calculate_variance=False`

- lifelines/fitters/cox_time_varying_fitter.py
- lifelines/fitters/coxph_fitter.py
Hello,
When pushing the solver to convergence, both `delta` and `newton_decrement` go to zero, so the displayed information looks like this when they becomes smaller than 1e-5:
With the proposed change a useful value is printed all along convergence:
> ENH use scientific number formatting for delta and newton decrement in Cox fitters

- lifelines/fitters/cox_time_varying_fitter.py
- lifelines/fitters/coxph_fitter.py
The stopping criterion of the Newton-Raphson method is mostly controlled by the parameter `precision`, but there is also a stopping criterion based on the relative improvement of the log-likelihood that so far used a hardcoded value of 1e-9. This PR exposes this parameter in the two NR solvers, with default value 1e-9 so as not to break existing code.
It also harmonizes stopping criteria between time varying and non time varying Cox Fitter
Finally it corrects the spelling of Raphson in docstrings, warning messages and comments
ping @Badr-Moufad
> expose r_precision parameter in Newton raphson solvers, correct typos

- docs/Survival Regression.rst
Fixes #1545: a model with the highest Log-Likelihood is the best one. Also, `random_state` prevents Pandas random sampling from generating a counterexample to what the documentation states (sometimes the "best model" could be the lower score)
> Fixed example and reproducibility for Log-likelihood

- lifelines/exceptions.py
- lifelines/fitters/mixins.py
- lifelines/tests/test_estimation.py
`cph.check_assumptions` can be tricky to use because it does not return something that can be used to infer the outcome of checking the assumptions (it returns axes [ref](https://github.com/CamDavidsonPilon/lifelines/blob/716b20441768ad399e40ff71baad8fea872c43e5/lifelines/fitters/mixins.py#L246))
I added an input parameter `throw_on_fail` where if True, when the check_assumptions fails the function will raise an error so the calling program can take appropriate action (eg discard the model results for that input / output pair).
1. I could write my own helper function using `proportional_hazard_test()` to do a similar check but still return the data in a way where I can detect if the assumption check failed.  I figured it'd be cool to add a fix to the library instead.
2. I could update the …
> Add throw_on_fail setting to check_assumptions

- lifelines/fitters/cox_time_varying_fitter.py
```
.../lib/python3.10/site-packages/lifelines/fitters/cox_time_varying_fitter.py:819: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '0.6058777002252564' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
```
this warning goes away with this change.
`pandas==2.1.4`
> address pandas deprecation warning

- lifelines/fitters/__init__.py
- lifelines/fitters/aalen_additive_fitter.py
- lifelines/fitters/coxph_fitter.py
- lifelines/utils/__init__.py
Changing `trapz` to `trapezoid` for scipy 1.14.0. 
Solution for Issue [#1618](https://github.com/CamDavidsonPilon/lifelines/issues/1618)
> Changing `trapz` to `trapezoid` for scipy 1.14.0.

- .github/workflows/ci.yaml
- CHANGELOG.md
- lifelines/fitters/coxph_fitter.py
- lifelines/fitters/npmle.py
- lifelines/fitters/piecewise_exponential_regression_fitter.py
- lifelines/generate_datasets.py
- lifelines/tests/test_estimation.py
- lifelines/tests/utils/test_utils.py
- lifelines/utils/__init__.py
- lifelines/version.py
- reqs/base-requirements.txt
- reqs/dev-requirements.txt
This is a "deprecation" and "futureWarning" release, and raises the lower bounds of SciPy and Pandas. 
The Pandas bump is pretty significant, but I figure: it's been out for a year, and if you're the type of person / org who is using scipy 0.14.0, and is interested in numpy 2.0, you're probably on a modern Pandas version. 
For users who don't want such a bump, they still have lifelines 0.28.0.
> bump to 0.29.0; bump scipy and pandas dependencies

- lifelines/statistics.py
The `print_summary` method in the `lifelines.statistics.StatisticalResult` class was not correctly handling the `decimals` argument when no explicit `style` was provided. This led to the output table displaying the default precision of 2 decimals, even if a different value was specified.
- **Problem:** the value of the 'decimals' argument did not propagate properly in the class. 
- **Solution:** set `self.decimals` so that the value is shared properly by all the methods of the class. 
- **Impact:** this fix ensures that the desired decimal precision is respected in the output table, even when no specific style is chosen.
For example, the issue was reproduced using the provided example with the results of the  `logrank_test` without explicit 'style' argument, resulting in a incorrect table …
> Bugfix: Incorrect Decimal Precision in StatisticalResult.print_summary (No Style)
