README.md
lifelines/plotting.py
lifelines/tests/test_estimation.py
lifelines/tests/test_plotting.py
requirements.txt
setup.py

This reduces the dep if you want a cleaner stack. Interestingly enough, Pandas doesn't have mpl as a dependency.

remove matplotlib from requirements, and making it an optional dep. 

---

CHANGELOG.md
lifelines/__init__.py
lifelines/_univariate_weibull.py
lifelines/estimation.py
lifelines/plotting.py
lifelines/tests/test_estimation.py
lifelines/tests/test_plotting.py
lifelines/tests/test_statistics.py
lifelines/tests/test_univariate_weibull.py
lifelines/tests/test_utils.py
lifelines/utils.py

This PR adds a WeibullFitter (which uses Newton's Method to find the parameters) and an ExponentialFitter (in another version I'll introduce a PieceWiseExponentialModel). There's also a whole lot of other stuff in this PR - ranging from api changes to cleaning up some code and tests. (lots of the latter).
@spacecowboy, wanna give this a look - sorry the diff is so noisy!

Adding univariate Weibull to the mix 

---

docs/Examples.rst
docs/Intro to lifelines.rst
docs/Quickstart.rst
docs/Survival Analysis intro.rst
docs/Survival Regression.rst
docs/index.rst

Hello! I just spent some time reading through the Lifelines Documentation to better understand the library. Fixed some small spelling errors, and hopefully can contribute more at the source level later on.

Editing Docs

---

docs/Examples.rst
docs/Quickstart.rst
lifelines/plotting.py
lifelines/utils/__init__.py
tests/utils/test_utils.py

This adds an at-risk column to the survival table

Add at risk

---

lifelines/fitters/weibull_fitter.py
lifelines/statistics.py
lifelines/utils/__init__.py
tests/test_statistics.py

closes #174 
tests will fail due to left-censor bug

adding sample size and power cals

---

.travis.yml

Also updates Conda urls to something that might be more future proof.

Update travis config to run on faster containers

---

docs/Survival Regression.rst

The link to the paper is broken, I have replace it for another with the same file.
Cheers

Broken link on the reference paper of Cox PH Model

---

lifelines/fitters/aalen_additive_fitter.py
tests/test_estimation.py

add logic to truncate hazard rates below 0, and fix some tests

---

CHANGELOG.md
lifelines/fitters/aalen_additive_fitter.py
lifelines/fitters/coxph_fitter.py
lifelines/utils/__init__.py
tests/test_estimation.py

I'd like some opinions on this, specifically the change for the `AalenAdditiveFitter.predict` method. @benkuhn and @spacecowboy can you please take a look?
Related to #147.

Remove predict method

---

docs/Survival Analysis intro.rst

Fixed typos and clarified a few sentences.

Update Survival Analysis intro.rst

---

docs/Intro to lifelines.rst

On line 58, instead of showing the first five records, I added a sample of ten records to give the user a better overall view of the data. 
On line 243, fixed a typo.

Update Intro to lifelines.rst

---

CHANGELOG.md
lifelines/fitters/coxph_fitter.py
tests/test_estimation.py

This will help users solve https://github.com/CamDavidsonPilon/lifelines/issues/242

moving correct place for check of all constant columns

---

docs/Intro to lifelines.rst

Thanks for the great documentation!

Fixing a typo... pendantic -> pedantic

---

docs/Quickstart.rst
docs/Survival Analysis intro.rst

Hi, I guess there is others, but that's it for the first pages.

Few typos on the documentation

---

CHANGELOG.md
docs/Intro to lifelines.rst
lifelines/fitters/aalen_additive_fitter.py
lifelines/plotting.py
tests/test_estimation.py
tests/test_plotting.py

remove ix from the api

---

.travis.yml
CHANGELOG.md
dev-requirements.txt
lifelines/plotting.py
tests/test_plotting.py
tests/utils/test_utils.py

fixing kmf plot

---

.travis.yml
CHANGELOG.md
lifelines/plotting.py
requirements.txt

this would drop matplotlib 1.x

simplify travis + drop matplotlib 1.x

---

lifelines/__init__.py
tests/test_estimation.py

Just checking the results of #327

adding test for last censorship

---

CHANGELOG.md
lifelines/fitters/__init__.py
lifelines/fitters/exponential_fitter.py
lifelines/fitters/weibull_fitter.py
tests/test_estimation.py

More accurate prediction methods parametrics univariate models.

Better predictions

---

lifelines/fitters/aalen_additive_fitter.py
lifelines/fitters/coxph_fitter.py
lifelines/utils/__init__.py
tests/test_estimation.py

adding check for numeric dtypes

---

lifelines/utils/__init__.py
tests/test_estimation.py

Changing survival_table_from_events so it generates float weights and subsequent calculations properly. Edited in reference to Issue #418

Float weights into survival_table_from_events

---

CHANGELOG.md
lifelines/fitters/__init__.py
tests/test_estimation.py

fix issue #466

---

lifelines/fitters/aalen_additive_fitter.py
lifelines/fitters/cox_time_varying_fitter.py
lifelines/fitters/coxph_fitter.py
lifelines/fitters/exponential_fitter.py
lifelines/fitters/kaplan_meier_fitter.py
lifelines/fitters/nelson_aalen_fitter.py
lifelines/fitters/weibull_fitter.py
lifelines/utils/__init__.py

As discussed in https://github.com/CamDavidsonPilon/lifelines/issues/533

Add Inf check for inputs

---

CHANGELOG.md
lifelines/fitters/coxph_fitter.py
tests/test_estimation.py

Also fixes a bug with strata + robust

Adding cluster arg to coxph

---

lifelines/fitters/coxph_fitter.py
tests/test_estimation.py

Fixes Issue #569 
Note: ome of the tests are failing for me.  Ive confirmed this isn't because of these changes (by running them before and after and noticing the same numbers).  I don't intend on fixing because I don't have the required background knowledge to do so (yet...) :-)

Remove predict_log_hazard_relative_to_mean

---

lifelines/plotting.py

Fix for Issue #560 (specifically `mccabe: MC0001 / plot_estimate is too complex (12)`)
Breaking these up have been harder than I hoped :-/.  That said, Ive managed to simplify plot_estimate!
I've done this by adding a "Config" class which takes in the inputs that need pre-processing and does that separately.  Not all the inputs need this, so it's not as awful as it could've been.
Note that I haven't tested this as I don't really understand how to use lifelines.  If you're able to easily manually test that would be awesome, otherwise I can have a go (any examples would be appreciated)

Decrease the McCabe complexity of plot_estimate

---

reqs/dev-requirements.txt

Add the pytest plugin [`pytest-icdiff`](https://github.com/hjwp/pytest-icdiff) for easier to read assertion result comparisons.

add pytest-icdiff

---

lifelines/fitters/__init__.py
lifelines/fitters/aalen_additive_fitter.py
lifelines/fitters/breslow_fleming_harrington_fitter.py
lifelines/fitters/cox_time_varying_fitter.py
lifelines/fitters/coxph_fitter.py
lifelines/fitters/exponential_fitter.py
lifelines/fitters/kaplan_meier_fitter.py
lifelines/fitters/nelson_aalen_fitter.py
lifelines/fitters/weibull_fitter.py
lifelines/plotting.py
lifelines/utils/__init__.py
reqs/dev-requirements.txt
tests/test_estimation.py
tests/utils/test_utils.py

Minor
* Typos fixed
* Docstrings were fixed where changes were obvious, otherwise left blank
* Unittests were conservatively modified to accomodate Windows specific issues (int32 vs int64)

fixed a few typos, docstrings, unittests working with Windows

---

lifelines/fitters/aalen_johansen_fitter.py
tests/test_estimation.py
tests/test_plotting.py

cc @pzivich for review
Mostly if this is moving lines around, or minor refactoring within functions. There's also a significant(?) API change, `variance` -> `variance_`, as this lines up with lifelines convention. 
I also fixed #688.

updates to AJF model

---

lifelines/fitters/cox_time_varying_fitter.py

removing axes from errorbar_kwargs if provided

---

docs/Survival Analysis intro.rst

Making changes in github browser editor as I see them. If you would prefer me to compile edits into one larger PR let me know. I can compile together and close these PRs

Add Numpy import

---

docs/Survival analysis with lifelines.rst

Fix minor typo in docs

---

lifelines/utils/sklearnAdapter.py

... s.a. crossvalidation and `cross_val_predict`.
Fixes #553

Added an adapter allowing to plug lifelines models to the stuff expecting sklearn models

---

setup.py

Q: does reqs/ need to be in the package now?

setup.py should look at requirements.txt

---

lifelines/fitters/coxph_fitter.py

When using multiple subplots, labels and ticks applied to the last one.

Set current axis

---

.travis.yml
setup.py

@Adsun701 are you able to give this a look? 
- I refactored things to look like other packages.
- I removed the readme and manifests from setup.py completely.

refector setup.py. Exclude adding info about readme and manifest

---

lifelines/fitters/__init__.py
lifelines/fitters/cox_time_varying_fitter.py
lifelines/fitters/coxph_fitter.py
lifelines/plotting.py
lifelines/statistics.py
lifelines/tests/utils/test_utils.py
lifelines/utils/__init__.py

Rmst plotting + variance calculation

---

docs/lifelines.fitters.rst
lifelines/__init__.py
lifelines/fitters/mixture_cure_fitter.py
lifelines/tests/test_estimation.py

This is a prototype of what a generic mixture cure fitter could look like. At the time of writing, it's probably too early to actually be merged.

Add a generic mixture cure fitter

---

CHANGELOG.md
README.md
docs/Compatibility with scikit-learn.rst
docs/Survival Regression.rst
lifelines/fitters/__init__.py
lifelines/fitters/coxph_fitter.py
lifelines/fitters/generalized_gamma_regression_fitter.py
lifelines/fitters/mixins.py
lifelines/fitters/spline_fitter.py
lifelines/tests/test_estimation.py
lifelines/utils/__init__.py
perf_tests/cp_perf_test.py

Multiple initial params

---

docs/Survival Regression.rst

Thank you for this clear and usable package and documentation!

DOC: little copyedit to survival regression docs

---

lifelines/plotting.py

plot_lifetimes now handles Pandas Series correctly.

Fixes issue #995.

---

docs/Examples.rst
docs/Survival Regression.rst
docs/Survival analysis with lifelines.rst
docs/Time varying survival regression.rst
docs/conftest.py
lifelines/utils/__init__.py
reqs/dev-requirements.txt

Quality of life changes for doc readers!

Docs improvement

---

docs/Examples.rst
lifelines/statistics.py
lifelines/tests/test_statistics.py

Added Wilcoxon, Tarone-Ware and Peto log-rank alternative tests

---

docs/Survival Regression.rst

fix coxph docs

---

examples/Customer Churn.ipynb

Corrected spelling on "hierarchical" on Jupyter notebook

Spelling correction

---

docs/Survival Regression.rst

extra 'model' in the sentence "The idea behind Cox's proportional hazard **model model** is that the...over time."

Update Survival Regression.rst

---

lifelines/utils/__init__.py

It looked outdated, tried to update that accordingly to other documenation

fix k_fold_cross_validation documentation

---

docs/Survival Regression.rst
lifelines/fitters/__init__.py
lifelines/tests/test_estimation.py
lifelines/tests/utils/test_utils.py
lifelines/utils/__init__.py
reqs/base-requirements.txt

Try formulaic

---

lifelines/fitters/cox_time_varying_fitter.py
lifelines/fitters/coxph_fitter.py

This is a fix for issue #1251 as noted.

PR for fixing elastic net penalty for cox models

---

lifelines/plotting.py

Fix sorting in interval-censored lifetimes plot

---

lifelines/calibration.py
lifelines/fitters/__init__.py
lifelines/fitters/coxph_fitter.py
lifelines/fitters/crc_spline_fitter.py

fixing self bug and issue #1387

---

docs/Examples.rst

adding a small explanation to one of the docs based on a raised issue

adding explanation to survival_difference_at_fixed_point_in_time_test

---

lifelines/fitters/__init__.py

Tiny change to fix https://github.com/CamDavidsonPilon/lifelines/issues/1512

fix datetime_is_numeric problem with pandas >= 2.0.0

---

docs/jupyter_notebooks/Proportional hazard assumption.ipynb

Brings documentation in line with https://github.com/CamDavidsonPilon/lifelines/pull/1518

Update Docs (Proportional hazard assumption.ipynb)

---

docs/Survival Regression.rst
docs/jupyter_notebooks/Custom Regression Models.ipynb
docs/jupyter_notebooks/Modelling time-lagged conversion rates.ipynb
examples/Custom Regression Models.ipynb
examples/Modelling time-lagged conversion rates.ipynb

This pull request fixes some small typos in the documentation.

doc: fix typos

---

lifelines/fitters/coxph_fitter.py

Issue : 1570 | Updated documentation for CoxPH Fitter

---

lifelines/fitters/breslow_fleming_harrington_fitter.py
lifelines/fitters/kaplan_meier_fitter.py

Closing #1574
I switched the values in the two columns, and kept the ordering lower, upper

switch confidence interval values
